### ISSUE TITLE
Package doesn't works with Flutter 3.22 WASM update

### ISSUE THREAD

**Issue by prateekmedia** [akvelon/flutter-code-editor#271]
On the web this package is broken due to the wasm update in flutter 3.22, It is related to change in dart:js package import on the web.

**Comment by morzan1001** [comment]
The migrationguide recommends the following:

Migrate usage of `dart:html` to` package:web`
Migrate usage of `dart:js`, `dart:js_util`, and `package:js` to `dart:js_interop`
This will fix compiling to WASM engine instead of just JavaScript on the web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

Unfortunately, replacing `dart:js` with `dart:js_interop` in the file [js_workarounds_web.dart](https://github.com/akvelon/flutter-code-editor/blob/dc2b466b7ae1023b6f13d2a8574c0276c21ffcf0/lib/src/code_field/js_workarounds/js_workarounds_web.dart) does not solve the problem :(

https://github.com/akvelon/flutter-code-editor/blob/dc2b466b7ae1023b6f13d2a8574c0276c21ffcf0/lib/src/code_field/js_workarounds/js_workarounds_web.dart#L2

**Comment by prateekmedia** [comment]
I had solved this already, this issue was just a placeholder.

**Comment by prateekmedia** [comment]
PR#272

**Comment by morzan1001** [comment]
> I had solved this already, this issue was just a placeholder.

Oh cool I had overlooked the mergerequest 👍

**Comment by prateekmedia** [comment]
Actually I just opened the PR, let me know if it works correctly with line numbers and all cause line numbers are going in offset for me.

**Comment by nausharipov** [comment]
Resolved in https://github.com/akvelon/flutter-code-editor/pull/272. Thank you.
