### ISSUE TITLE
TabModifier doesn't work when pasting 2 or more tabs

### ISSUE THREAD

**Issue by nausharipov** [akvelon/flutter-code-editor#69]
<img width="311" alt="Screen Shot 2022-09-15 at 14 03 22" src="https://user-images.githubusercontent.com/31556582/190349624-23bd1e42-d301-432f-8ef5-5b200b484a5a.png">

**Comment by alexeyinkin** [comment]
Although tabs are fixed in the Flutter's master channel, this issue is a matter of consistency to us.

We do want to let a user work with consistent spaces. And we do want to let a user work with raw text as they want (preserving both spaces and tabs).

If we have a mode of replacing spaces with tabs at all, it should be consistent and cover pasting as well.

Some IDEs support loading as-is, inserting spaces on tab key, and preserving pasting. But none convert to tabs on loading while preserving pasting.

**Comment by alexeyinkin** [comment]
https://github.com/akvelon/flutter-code-editor/pull/87
